name: jzphotographer
favicon: null
layout_spectrum: 0.78519
typography_spectrum: 0.1189283
title: JZPhotographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8774186
  lightness: 0.477601
  saturation: 0.4891551
  rhythmicContrast: 0.4247406
purpose: []
