layout_spectrum: 0.6488535
typography_spectrum: 0.1189283
color:
  saturation: 0.4891551
  lightness: 0.477601
  brandStrength: 0.8774186
  rhythmicContrast: 0.4247406
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: jzphotographer
